---CREATE THE DATABASE HERE

CREATE DATABASE CUSTOMER
USE CUSTOMER

--HERE WE IMPORTED THE FLAT FILE OF CSV WHICH WE HAVE DONE ALL THE ANALYSIS IN JUPYTER NOTEBOOK

SELECT * FROM Customer

--Q1.RETRIEVE THE CUSTOMERS WHO ARE MALE AND THE AGE IS ABOVE 50
select * from customer where gender = 'male' and age > 50


--Q2. What is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--Q3. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from Customer 
where discount_applied = 'Yes' and 
purchase_amount >=(select AVG(purchase_amount) from Customer)

--Q4. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased , AVG(review_rating) as 'Average review rating'
from Customer
group by item_purchased
order by AVG(review_rating) desc

--Q5. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type , AVG(purchase_amount) 'Average Purchase Amounts'
from Customer
where  shipping_type in ('Standard','Express')
group by shipping_type

--Q6. That subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status , count(customer_id) as 'total_customers',
AVG(purchase_amount) as avg_spend,
sum(purchase_amount) as total_revenue
from Customer
group by subscription_status 
order by avg_spend, total_revenue

--Q7. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT top 5 item_purchased,
       (100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*)) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC

--Q8. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as(
select customer_id,previous_purchases,
CASE when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end customer_segment
from Customer)

select customer_segment,count(*) as 'Number of Customers'
from customer_type
group by customer_segment

--Q9. What are the top 3 most purchased products within each category? 
with item_counts as(
select item_purchased,category,
count(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY count(customer_id) DESC) AS Item_Rank
FROM CUSTOMER
group by item_purchased,category)

select item_purchased,category,total_orders,Item_Rank
from item_counts
where Item_Rank<=3



